import Navbar from '@/components/Navbar'
import './globals.css'
import AuthProvider from '@/SessionProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <AuthProvider>
          <div className='max-w-screen-lg	m-auto'>
            <Navbar />
        {children}
        </div>  
          </AuthProvider>
        </body>
    </html>
  )
}
