import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='max-w-screen-lg	m-auto'>
        {children}

        </div>        
        </body>
    </html>
  )
}
